name: Discord Gemini Bot

on:
  schedule:
    - cron: '0 */6 * * *'  # 6 saatte bir
  workflow_dispatch:  # Manuel tetikleme

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py google-generativeai

    - name: Run bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        python bot.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add chat_histories.json || exit 0
        git diff --cached --quiet && echo "No changes to commit" || (git commit -m "Update chat history" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
