name: Run Discord Bot

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: FFmpeg kurulumu
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Discord botu başlat
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python bot.py
