name: Run Discord Bot (6h loop)

on:
  workflow_dispatch:

concurrency:
  group: discord-bot
  cancel-in-progress: true   # aynı anda 2 iş çalışmaz

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 370     # 6h 10min max runtime (fail-safe)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Discord Bot (6h)
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          python bot.py &
          BOT_PID=$!
          sleep 21600   # 6 saat
          kill $BOT_PID || true

      - name: Trigger next run
        run: |
          gh workflow run "Run Discord Bot (6h loop)" --ref ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
