name: Run Discord Bot

on:
  push:
    paths:
      - 'user_data.json'  # user_data.json değiştiğinde tetiklenir
  workflow_dispatch:  # Manuel çalıştırma

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run Discord Bot
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python bot.py

    - name: Commit & push updated user_data.json
      if: always()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add user_data.json
        git commit -m "Update user_data.json [skip ci]" || echo "No changes to commit"
        git push
